### ISSUE TITLE
Cannot start server

### ISSUE THREAD

**Issue by punkpeye** [reminia/zendesk-mcp-server#1]
I'm trying to start this server so I can mark the associated [listing](https://glama.ai/mcp/servers/6bnpa1uoes) as tested.

### Current Behavior

This is my `Dockerfile`:

```Dockerfile
FROM python:3.12

RUN pip install uv

WORKDIR /app

RUN git clone https://github.com/reminia/zendesk-mcp-server .



RUN uv sync

CMD ["uv", "run", "zendesk"]
```

When I run it, I get the following error:

```
Traceback (most recent call last):
  File "/app/.venv/bin/zendesk", line 5, in <module>
    from zendesk_mcp_server import main
  File "/app/src/zendesk_mcp_server/__init__.py", line 3, in <module>
    from . import server
  File "/app/src/zendesk_mcp_server/server.py", line 20, in <module>
    zendesk_client = ZendeskClient(
                     ^^^^^^^^^^^^^^
  File "/app/src/zendesk_mcp_server/zendesk_client.py", line 12, in __init__
    self.client = Zenpy(
                  ^^^^^^
  File "/app/.venv/lib/python3.12/site-packages/zenpy/__init__.py", line 120, in __init__
    session = self._init_session(email, token, oauth_token,
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/.venv/lib/python3.12/site-packages/zenpy/__init__.py", line 226, in _init_session
    raise ZenpyException(
zenpy.lib.exception.ZenpyException: password, token or oauth_token are required! {'self': <zenpy.Zenpy object at 0xffffbbc68f50>, 'email': None, 'token': None, 'oath_token': None, 'password': None, 'session': <requests.sessions.Session object at 0xffffba6d5a30>, 'anonymous': False}

```

### Expected Behavior

The server should start correctly when using `uv run`.

### Suggested Improvement

I believe README is missing description of a required env variable needed to start the server.

Could you provide a complete example in the README showing how to start the server using uv run?

This would improve usability for developers and help automated systems like [Glama](https://glama.ai/mcp/servers) to test the server

**Comment by reminia** [comment]
@punkpeye  check the Setup part of readme, you need to seup zendesk credentials as env varaibles.

**Comment by punkpeye** [comment]
^ This is an automated error message.

It is saying that AI agent that is trying to understand how to run this MVP server cannot figure out how to start the server based on the available information in README.

This could be fixed by adding examples of:

```
ZENDESK_SUBDOMAIN=xxx
ZENDESK_EMAIL=xxx
ZENDESK_API_KEY=xxx
```

directory to README
